### ISSUE TITLE
could not pass through messageTTL as 0

### ISSUE THREAD

**Issue by ellachen1234** [manuel-sousa/ansible-modules-rabbitmq#1]
In current implementation, it doesn't allow to pass though messageTTL as 0 when creating a queue

**Comment by manuel-sousa** [comment]
Hi, don't know if it's an issue with current implementation but this has been merged to rabbitmq.
If it's an issue there please submit the report.

**Comment by ellachen1234** [comment]
Where can I submit the report? In line: 213: "if module.params[k]:" it will ignore zero value.

**Comment by manuel-sousa** [comment]
It's been merged here:
https://github.com/ansible/ansible

**Comment by ellachen1234** [comment]
Thanks. I have reported there.
